### ISSUE TITLE
Tests are failing on `master`

### ISSUE THREAD

**Issue by posita** [trezor/python-mnemonic#27]
Possibly related to #10, but running tests results in many failures:

```
% tox -e py27
GLOB sdist-make: /.../posita/python-mnemonic/setup.py
py27 inst-nodeps: /.../posita/python-mnemonic/.tox/dist/mnemonic-0.12.zip
py27 installed: mnemonic==0.12,pbkdf2==1.3,wheel==0.24.0
py27 runtests: PYTHONHASHSEED='2037693756'
py27 runtests: commands[0] | python test_mnemonic.py
...FLanguage 'english'
Language 'japanese'
------------------------------------
Test of word prefixes:
Duplicate prefix あ<E3> for words ['\xe3\x81\x82\xe3\x81\x84\xe3\x81\x93\xe3\x81\x8f\xe3\x81\x97\xe3\x82\x93', '\xe3\x81\x82\xe3\x81\x84\xe3\x81\x95\xe3\x81\xa4', '\xe3\x81\x82\xe3\x81\x84\xe3\x81\x9f\xe3\x82\x99', '\xe3\x81\x82\xe3\x81\x8a\xe3\x81\x9d\xe3\x82\x99\xe3\x82\x89', '\xe3\x81\x82\xe3\x81\x8b\xe3\x81\xa1\xe3\x82\x83\xe3\x82\x93', '\xe3\x81\x82\xe3\x81\x8d\xe3\x82\x8b', '\xe3\x81\x82\xe3\x81\x91\xe3\x81\x8b\xe3\x82\x99\xe3\x81\x9f', '\xe3\x81\x82\xe3\x81\x91\xe3\x82\x8b', '\xe3\x81\x82\xe3\x81\x93\xe3\x81\x8b\xe3\x82\x99\xe3\x82\x8c\xe3\x82\x8b', '\xe3\x81\x82\xe3\x81\x95\xe3\x81\x84', '\xe3\x81\x82\xe3\x81\x95\xe3\x81\xb2', '\xe3\x81\x82\xe3\x81\x97\xe3\x81\x82\xe3\x81\xa8', '\xe3\x81\x82\xe3\x81\x97\xe3\x82\x99\xe3\x82\x8f\xe3\x81\x86', '\xe3\x81\x82\xe3\x81\x99\xe3\x82\x99\xe3\x81\x8b\xe3\x82\x8b', '\xe3\x81\x82\xe3\x81\x99\xe3\x82\x99\xe3\x81\x8d', '\xe3\x81\x82\xe3\x81\x9d\xe3\x81\xb5\xe3\x82\x99', '\xe3\x81\x82\xe3\x81\x9f\xe3\x81\x88\xe3\x82\x8b', '\xe3\x81\x82\xe3\x81\x9f\xe3\x81\x9f\xe3\x82\x81\xe3\x82\x8b', '\xe3\x81\x82\xe3\x81\x9f\xe3\x82\x8a\xe3\x81\xbe\xe3\x81\x88', '\xe3\x81\x82\xe3\x81\x9f\xe3\x82\x8b', '\xe3\x81\x82\xe3\x81\xa4\xe3\x81\x84', '\xe3\x81\x82\xe3\x81\xa4\xe3\x81\x8b\xe3\x81\x86', '\xe3\x81\x82\xe3\x81\xa3\xe3\x81\x97\xe3\x82\x85\xe3\x81\x8f', '\xe3\x81\x82\xe3\x81\xa4\xe3\x81\xbe\xe3\x82\x8a', '\xe3\x81\x82\xe3\x81\xa4\xe3\x82\x81\xe3\x82\x8b', '\xe3\x81\x82\xe3\x81\xa6\xe3\x81\xaa', '\xe3\x81\x82\xe3\x81\xa6\xe3\x81\xaf\xe3\x81\xbe\xe3\x82\x8b', '\xe3\x81\x82\xe3\x81\xb2\xe3\x82\x8b', '\xe3\x81\x82\xe3\x81\xb5\xe3\x82\x99\xe3\x82\x89', '\xe3\x81\x82\xe3\x81\xb5\xe3\x82\x99\xe3\x82\x8b', '\xe3\x81\x82\xe3\x81\xb5\xe3\x82\x8c\xe3\x82\x8b', '\xe3\x81\x82\xe3\x81\xbe\xe3\x81\x84', '\xe3\x81\x82\xe3\x81\xbe\xe3\x81\xa8\xe3\x82\x99', '\xe3\x81\x82\xe3\x81\xbe\xe3\x82\x84\xe3\x81\x8b\xe3\x81\x99', '\xe3\x81\x82\xe3\x81\xbe\xe3\x82\x8a', '\xe3\x81\x82\xe3\x81\xbf\xe3\x82\x82\xe3\x81\xae', '\xe3\x81\x82\xe3\x82\x81\xe3\x82\x8a\xe3\x81\x8b', '\xe3\x81\x82\xe3\x82\x84\xe3\x81\xbe\xe3\x82\x8b', '\xe3\x81\x82\xe3\x82\x86\xe3\x82\x80', '\xe3\x81\x82\xe3\x82\x89\xe3\x81\x84\xe3\x81\x8f\xe3\x82\x99\xe3\x81\xbe', '\xe3\x81\x82\xe3\x82\x89\xe3\x81\x97', '\xe3\x81\x82\xe3\x82\x89\xe3\x81\x99\xe3\x81\x97\xe3\x82\x99', '\xe3\x81\x82\xe3\x82\x89\xe3\x81\x9f\xe3\x82\x81\xe3\x82\x8b', '\xe3\x81\x82\xe3\x82\x89\xe3\x82\x86\xe3\x82\x8b', '\xe3\x81\x82\xe3\x82\x89\xe3\x82\x8f\xe3\x81\x99', '\xe3\x81\x82\xe3\x82\x8a\xe3\x81\x8b\xe3\x82\x99\xe3\x81\xa8\xe3\x81\x86', '\xe3\x81\x82\xe3\x82\x8f\xe3\x81\x9b\xe3\x82\x8b', '\xe3\x81\x82\xe3\x82\x8f\xe3\x81\xa6\xe3\x82\x8b', '\xe3\x81\x82\xe3\x82\x93\xe3\x81\x84', '\xe3\x81\x82\xe3\x82\x93\xe3\x81\x8b\xe3\x82\x99\xe3\x81\x84', '\xe3\x81\x82\xe3\x82\x93\xe3\x81\x93', '\xe3\x81\x82\xe3\x82\x93\xe3\x81\x9b\xe3\x82\x99\xe3\x82\x93', '\xe3\x81\x82\xe3\x82\x93\xe3\x81\xa6\xe3\x81\x84', '\xe3\x81\x82\xe3\x82\x93\xe3\x81\xaa\xe3\x81\x84', '\xe3\x81\x82\xe3\x82\x93\xe3\x81\xbe\xe3\x82\x8a']
...
Duplicate prefix ろ<E3> for words ['\xe3\x82\x8d\xe3\x81\x86\xe3\x81\x8b', '\xe3\x82\x8d\xe3\x81\x86\xe3\x81\x93\xe3\x82\x99', '\xe3\x82\x8d\xe3\x81\x86\xe3\x81\x97\xe3\x82\x99\xe3\x82\x93', '\xe3\x82\x8d\xe3\x81\x86\xe3\x81\x9d\xe3\x81\x8f', '\xe3\x82\x8d\xe3\x81\x8f\xe3\x81\x8b\xe3\x82\x99', '\xe3\x82\x8d\xe3\x81\x93\xe3\x81\xa4', '\xe3\x82\x8d\xe3\x81\x97\xe3\x82\x99\xe3\x81\x86\xe3\x82\x89', '\xe3\x82\x8d\xe3\x81\x97\xe3\x82\x85\xe3\x81\xa4', '\xe3\x82\x8d\xe3\x81\x9b\xe3\x82\x93', '\xeF.F..FE
======================================================================
ERROR: test_vectors (__main__.MnemonicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mnemonic.py", line 50, in test_vectors
    self._check_list(lang, vectors[lang])
  File "test_mnemonic.py", line 42, in _check_list
    self.assertIs(mnemo.check(v[1]), True)
  File "/.../posita/python-mnemonic/mnemonic/mnemonic.py", line 142, in check
    if self.detect_language(mnemonic.replace('\xe3\x80\x80', ' ')) == 'japanese':
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 0: ordinal not in range(128)

======================================================================
FAIL: test_lengths (__main__.MnemonicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mnemonic.py", line 83, in test_lengths
    self.assertListEqual(words, [])
AssertionError: Lists differ: ['\xe3\x81\x82\xe3\x81\x84\xe3... != []

First list contains 2048 additional elements.
First extra element 0:
あいこくしん

Diff is 111841 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_root_len (__main__.MnemonicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mnemonic.py", line 129, in test_root_len
    self.assertEqual(problems_found, 0)
AssertionError: 2004 != 0

======================================================================
FAIL: test_sorted_unique (__main__.MnemonicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mnemonic.py", line 108, in test_sorted_unique
    self.assertListEqual(unique, mnemo.wordlist)
AssertionError: Lists differ: ['\xe3\x81\x82\xe3\x81\x84\xe3... != ['\xe3\x81\x82\xe3\x81\x84\xe3...

First differing element 20:
あっしゅく
あつい

Diff is 127522 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_validchars (__main__.MnemonicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mnemonic.py", line 93, in test_validchars
    self.assertIn(l, 'abcdefghijklmnopqrstuvwxyz')
AssertionError: '\xaf' not found in 'abcdefghijklmnopqrstuvwxyz'

----------------------------------------------------------------------
Ran 11 tests in 26.582s

FAILED (failures=4, errors=1)
3\x82\x8d\xe3\x81\xa6\xe3\x82\x93', '\xe3\x82\x8d\xe3\x82\x81\xe3\x82\x93', '\xe3\x82\x8d\xe3\x82\x8c\xe3\x81\xa4', '\xe3\x82\x8d\xe3\x82\x93\xe3\x81\x8d\xe3\x82\x99', '\xe3\x82\x8d\xe3\x82\x93\xe3\x81\xaf\xe3\x82\x9a', '\xe3\x82\x8d\xe3\x82\x93\xe3\x81\xb5\xe3\x82\x99\xe3\x82\x93', '\xe3\x82\x8d\xe3\x82\x93\xe3\x82\x8a']
Duplicate prefix ろ<E3> for words ['\xe3\x82\x8d\xe3\x81\x86\xe3\x81\x8b', '\xe3\x82\x8d\xe3\x81\x86\xe3\x81\x93\xe3\x82\x99', '\xe3\x82\x8d\xe3\x81\x86\xe3\x81\x97\xe3\x82\x99\xe3\x82\x93', '\xe3\x82\x8d\xe3\x81\x86\xe3\x81\x9d\xe3\x81\x8f', '\xe3\x82\x8d\xe3\x81\x8f\xe3\x81\x8b\xe3\x82\x99', '\xe3\x82\x8d\xe3\x81\x93\xe3\x81\xa4', '\xe3\x82\x8d\xe3\x81\x97\xe3\x82\x99\xe3\x81\x86\xe3\x82\x89', '\xe3\x82\x8d\xe3\x81\x97\xe3\x82\x85\xe3\x81\xa4', '\xe3\x82\x8d\xe3\x81\x9b\xe3\x82\x93', '\xe3\x82\x8d\xe3\x81\xa6\xe3\x82\x93', '\xe3\x82\x8d\xe3\x82\x81\xe3\x82\x93', '\xe3\x82\x8d\xe3\x82\x8c\xe3\x81\xa4', '\xe3\x82\x8d\xe3\x82\x93\xe3\x81\x8d\xe3\x82\x99', '\xe3\x82\x8d\xe3\x82\x93\xe3\x81\xaf\xe3\x82\x9a', '\xe3\x82\x8d\xe3\x82\x93\xe3\x81\xb5\xe3\x82\x99\xe3\x82\x93', '\xe3\x82\x8d\xe3\x82\x93\xe3\x82\x8a']
...
Duplicate prefix わ<E3> for words ['\xe3\x82\x8f\xe3\x81\x8b\xe3\x81\x99', '\xe3\x82\x8f\xe3\x81\x8b\xe3\x82\x81', '\xe3\x82\x8f\xe3\x81\x8b\xe3\x82\x84\xe3\x81\xbe', '\xe3\x82\x8f\xe3\x81\x8b\xe3\x82\x8c\xe3\x82\x8b', '\xe3\x82\x8f\xe3\x81\x97\xe3\x81\xa4', '\xe3\x82\x8f\xe3\x81\x97\xe3\x82\x99\xe3\x81\xbe\xe3\x81\x97', '\xe3\x82\x8f\xe3\x81\x99\xe3\x82\x8c\xe3\x82\x82\xe3\x81\xae', '\xe3\x82\x8f\xe3\x82\x89\xe3\x81\x86', '\xe3\x82\x8f\xe3\x82\x8c\xe3\x82\x8b']
------------------------------------
Test of sorted and unique wordlists:
Language 'english'
Language 'japanese'
Language 'english'
Language 'japanese'
ERROR: InvocationError: '/.../posita/python-mnemonic/.tox/py27/bin/python test_mnemonic.py'
___________________________________ summary ____________________________________
ERROR:   py27: commands failed
```

**Comment by posita** [comment]
I've tried several recent commits in `master`, and I see similar failures in a lot of places.

**Comment by prusnak** [comment]
Most of these tests does not make sense for japanese so I disabled them in 89463bdb16a878868ed5f2d077411f6818fb7887
