### ISSUE TITLE
seed = mnemo.to_seed(words, passphrase="") get error bad key length

### ISSUE THREAD

**Issue by arlicle** [trezor/python-mnemonic#96]
mnemo = Mnemonic("english")
words = mnemo.generate(strength=256)
seed = mnemo.to_seed(words, passphrase="")
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/edison/Library/Python/3.8/lib/python/site-packages/mnemonic/mnemonic.py", line 239, in to_seed
    stretched = hashlib.pbkdf2_hmac(
ValueError: [digital envelope routines: CRYPTO_internal] bad key length
```

**Comment by prusnak** [comment]
Works for me here. Sounds like your installation is funky.

**Comment by arlicle** [comment]
My systerm is mac 12.1 (21C52)

**Comment by prusnak** [comment]
> My systerm is mac 12.1 (21C52)

Works just fine with system Python 3.8.9 on macOS 12.3
